package project.com.equake;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

/**
 * Created by G Anudeep Reddy on 17-Jul-17.
 */

@DynamoDBTable(tableName = "PhoneReadings")
public class PhoneReading {
    private String sNo;
    private String phoneId;
    private String latitude;
    private String longitude;

    @DynamoDBHashKey(attributeName = "SNo")
    @DynamoDBAutoGeneratedKey

    public void setSno(String sNo)  {   this.sNo = sNo; }
    public String getSno()  {   return sNo; }


    public void setPhoneId(String phoneId)  {   this.phoneId = phoneId; }
    public String getPhoneId()  {   return phoneId; }

    public void setLatitude(String latitude)  { this.latitude = latitude;   }
    public String getLatitude()  {   return latitude;   }

    public void setLongitude(String longitude)  {   this.longitude = longitude; }
    public String getLongitude()  {   return longitude; }
}
